### ISSUE TITLE
easyC connection ports pinout (JST SH connector pinout)

### ISSUE THREAD

**Issue by B48D81EFCC** [SolderedElectronics/easyC-adapter-hardware-design#1]
Hello,

I can't find any documentation about the easyC Adapter's easyC connection ports.
The pinout of the four plated though-holes is documentation, but unfortunately I can't find anything about the easyC connection ports (JST SH connector).

Can you please provide information about the pinout?
Ultimately I want to know if the easyC cables and easyC adapter are compatible / interchangeable with the Sparkfun Qwiic counterparts.

Thanks and best regards

**Comment by rsoric** [comment]
Hi @B48D81EFCC,

sorry for a bit of a delayed reply, this issue came up while I was personally on PTO.
To quickly reply, they are fully compatible and interchangeable with Sparkfun Qwiic and Adafruit Stemma QT, as is noted here: https://soldered.com/easyC/ (section Is easyC compatible with other systems?).

There you can find some more info about the pinout.

Hope that's helpful
-Rob
